
server:
  port: 8822

spring:
  application:
    name: user-service
  cloud:
    config:
      name: user-service
      uri: http://localhost:8855/
      profile: dev
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@localhost:8800/eureka/
