server:
  port: 8888

spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ba1xing/spring-cloud-config.git
          search-paths: config-repo
          username: ba1xing@163.com
          password:
